// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  module.exports = function(AV) {
    return function() {
      return function(req, res, next) {
        if (AV.Cloud.__prod && (!req.secure)) {
          return res.redirect('https://' + req.get('host') + req.originalUrl);
        } else {
          return next();
        }
      };
    };
  };

}).call(this);
